### ISSUE TITLE
Suggestion custom GUIs

### ISSUE THREAD

**Issue by Lordphiphi** [Frektip/Technical-Enchant-Renewed#12]
For custom GUIs, you can simply use a character with a custom font in the title, so that there are no items in the GUI (apart from the few clickable places), giving a more vanilla look.
Btw sorry, I don't know how to put a label

**Comment by Frektip** [comment]
I know that that would be more convenient, however TE+ was designed to be played without the Resource Pack, that's why I decided to leave it as that (with the stained glass panes that have a CMD tag).

**Comment by Lordphiphi** [comment]
Ah ok, why this choice? I mean, if you install it for yourself, you have to install the datapack anyway, so it's not much more, and if you play it on a server, in any case you don't have to install anything (because of the forcepack).

**Comment by Frektip** [comment]
The initial purpose of the pack was that you don't need 100% a RP required in order to be played. Maybe the standards have changed a bit other the years. 

Back then, datapacks with a resource pack dependency were less popular because of that "extra step" you need to make to have the full experience. Also some tools weren't available for resource packs (mainly for translated text).

Of course I would do several changes if I ever decide to make TE+ with a Resource Pack dependency from the start.

**Comment by Lordphiphi** [comment]
Okok, yes clearly it's something recent, but as resource packs get more and more powerful, and datapacks more and more ambicious, it makes sense that more and more datapacks have resource packs required.

**Comment by Frektip** [comment]
Yeah, it is a trend that I should consider taking into account for future projects.
