### ISSUE TITLE
Double Curses

### ISSUE THREAD

**Issue by Johannes-Sch** [Frektip/Technical-Enchant-Renewed#6]
Hi, sometimes when extracting enchantments while there is a curse on the item the last enchantment can't be extracted, but the curse gets doubled somehow. The Item can be enchanted again after that.

In this example the axe had Life+ V, some other enchantments and Curse of Fear. Everything could be extracted onto books but Life+, after removing the axe from the anvil, the curse was doubled. After enchanting it again (Table) and disenchanting (Grind stone) the curse gets added again every time.

![grafik](https://user-images.githubusercontent.com/36738886/212574021-752449d8-dccd-4f6e-98f7-db9e61d5c72c.png)

Thanks and kind regards

**Comment by Johannes-Sch** [comment]
In addition to that: I made too more iron axes after that, enchanted them and got Curse of Fear 4x every time but with different other enchantments.

The first one (again disenchanted):
![grafik](https://user-images.githubusercontent.com/36738886/212574475-03e77ea7-3d82-4aad-8607-e11e7a2a0446.png)

2.
![grafik](https://user-images.githubusercontent.com/36738886/212574452-a64735b7-ea78-419e-974d-c540652497b8.png)

3.
![grafik](https://user-images.githubusercontent.com/36738886/212574467-5db6eb9d-1fbe-4854-b4c5-e12192c2801a.png)

**Comment by Frektip** [comment]
~~I would appreciate if you can type `/data get entity @s SelectedItem.tag` while holding that item and show me the nbt data.~~

~~I think that bug happens because you have a ghost enchantment (but I'm not sure), I fixed that bug in the last update and I recently updated the datapack version to v7.3.1~~

**EDIT:** I found what's causing the problem, I think is something that only happens with the enchanting table, though if you can give me more methods to get into that situation, I'm open to test that out. 

Tip: before doing anything else type this command: `/data remove storage teplus:item_lore CurrentLore`

**Comment by Frektip** [comment]
I've updated the datapack version to fix that issue, I'm not sure when I will be able to bring the same update for the mod versions (sorry)

**Comment by Johannes-Sch** [comment]
Thanks for your fast reply, I'm always impressed, how fast you manage to solve these problems ^^.
I Updated our Server World to the newest version and if it happens again I will let you know.

This was btw the axe from yesterday:
![grafik](https://user-images.githubusercontent.com/36738886/212757205-4d72f190-f92f-4316-a11a-6f37342b9d5c.png)

**Comment by Frektip** [comment]
yeah, v7.3.1b should fix that issue (for new items)
